# Kreuzstich
# Copyright (c) 2013, 2026 Fabien Pollet <polletfa@posteo.de>
# MIT License, see LICENSE file.

name: Install dependencies

inputs:
    config:
        description: windows, linux-gcc, linux-clang, macos
        required: true
    target:
        description: all, gui-web, gui-desktop
        required: false
        default: all

runs:
    using: composite
    steps:
        - name: Load dependency versions
          shell: bash
          run: cat .github/dependencies.conf >> $GITHUB_ENV

        - name: Set variables
          shell: bash
          run: |
              case ${{ inputs.config }} in
              windows)
                echo "QT_HOST=windows" >> $GITHUB_ENV
                echo "QT_ARCH=win64_msvc2022_64" >> $GITHUB_ENV
                ;;
              linux-gcc | linux-clang)
                echo "QT_HOST=linux" >> $GITHUB_ENV
                echo "QT_ARCH=linux_gcc_64" >> $GITHUB_ENV
                ;;
              macos)
                echo "QT_HOST=mac" >> $GITHUB_ENV
                echo "QT_ARCH=clang_64" >> $GITHUB_ENV
                ;;
              *)
                echo "::error::Invalid config selected"
                exit 1
                ;;
              esac

        - name: Install Clang 19
          if: ${{ inputs.config == 'linux-clang' }}
          shell: bash
          run: |
              wget https://apt.llvm.org/llvm.sh
              chmod +x llvm.sh
              sudo ./llvm.sh 19

        - name: Install Qt
          if: ${{ inputs.target == 'all' || inputs.target == 'gui-desktop' }}
          uses: jurplel/install-qt-action@v4
          with:
              version: ${{ env.QT_VERSION }}
              # Known issue, fixed but not yet released:
              # - https://github.com/jurplel/install-qt-action/issues/374
              # - https://github.com/miurahr/aqtinstall/issues/959
              aqtsource: 'git+https://github.com/miurahr/aqtinstall.git@refs/pull/1000/head'
              host: ${{ env.QT_HOST }}
              arch: ${{ env.QT_ARCH }}
              target: 'desktop'
              cache: true

        - name: Install Node.js
          if: ${{ inputs.target == 'all' || inputs.target == 'gui-web' }}
          uses: actions/setup-node@v6
          with:
              node-version: ${{ env.NODE_VERSION }}

        - name: Install EMSDK
          if: ${{ inputs.target == 'all' || inputs.target == 'gui-web' }}
          uses: emscripten-core/setup-emsdk@v15
          with:
              version: ${{ env.EMSDK_VERSION }}
              actions-cache-folder: 'emsdk-cache'
