# Kreuzstich
# Copyright (c) 2013, 2026 Fabien Pollet <polletfa@posteo.de>
# MIT License, see LICENSE file.

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/resources/server-config"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/server-config/services/kreuzstich-prod"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/server-config/services/kreuzstich-int"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/docker/kreuzstich-prod"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/docker/kreuzstich-prod-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/docker/kreuzstich-int"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/docker/kreuzstich-int-api"
    schedule:
      interval: "weekly"
