# Kreuzstich
# Copyright (c) 2013, 2026 Fabien Pollet <polletfa@posteo.de>
# MIT License, see LICENSE file.

version: 2

updates:
  - package-ecosystem: "docker-compose"
    directory: "/resources/server-config"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "docker-compose"
    directory: "/resources/server-config/services/kreuzstich-prod"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "docker-compose"
    directory: "/resources/server-config/services/kreuzstich-int"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "/resources/docker/kreuzstich"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "docker"
    directory: "/resources/docker/kreuzstich-api"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/src/gui-web"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      npm-vitest:
        patterns: ["vitest", "@vitest/*"]
      npm-angular:
        patterns: ["@angular/*"]

  - package-ecosystem: "npm"
    directory: "/src/data-web"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      npm-vitest:
        patterns: ["vitest", "@vitest/*"]

  - package-ecosystem: "npm"
    directory: "/tests/wrapper-wasm"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      npm-vitest:
        patterns: ["vitest", "@vitest/*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
