# Kreuzstich
# Copyright (c) 2013, 2026 Fabien Pollet <polletfa@posteo.de>
# MIT License, see LICENSE file.

server {
    listen 443 ssl;
    http2 on;
    server_name int.kreuzstich.art;

    ssl_certificate /etc/letsencrypt/live/kreuzstich.art/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kreuzstich.art/privkey.pem;

    include /etc/nginx/services.conf.d/int.kreuzstich.art/locations.*.conf;
}
