# Kreuzstich
# Copyright (c) 2013, 2026 Fabien Pollet <polletfa@posteo.de>
# MIT License, see LICENSE file.

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    error_log /var/log/nginx/error.log error;

    sendfile        on;

    keepalive_timeout  65;

    #
    # Let's Encrypt certificate verification uses the so-called ACME Challenge.
    # It requires the URl http://<domain>/.well-known/acme-challenge to be accessible
    # and mapped to a directory where certbot will write a temporary token when requesting
    # a certificate. This is why we need to port 80 to be open.
    #
    server {
        listen 80 default_server;
        server_name _;

        location /.well-known/acme-challenge/ {
            root /etc/letsencrypt/acme-challenge;
        }

        location / {
            return 301 https://$host$request_uri; # Redirect everything else to https
        }
    }

    #
    # "catch-all" server for invalid subdomains
    #
    server {
        listen 443 ssl default_server;
        server_name _;
        ssl_reject_handshake on;
    }

    #
    # Domains
    #
    include /etc/nginx/domains.conf.d/*.conf;
}
