# Kreuzstich
# Copyright (c) 2013, 2026 Fabien Pollet <polletfa@posteo.de>
# MIT License, see LICENSE file.

networks:
  kreuzstich-int-backend:
    internal: true
  kreuzstich-int:
    internal: true

services:
  kreuzstich-int-database:
    container_name: kreuzstich-int-database
    image: postgres:18
    env_file:
      # For environment variables that should not be committed:
      # - POSTGRES_PASSWORD (kreuzstich-int-database)
      # - KREUZSTICH_DATA_WEB_DB_PASSWORD (kreuzstich-int-api)
      # - KREUZSTICH_DATA_WEB_JWT_SECRET (kreuzstich-int-api)
      - ./secrets.env
    environment:
      - POSTGRES_USER=kreuzstich
      - POSTGRES_DB=kreuzstich
    networks:
      - kreuzstich-int-backend
    volumes:
      - /etc/localtime:/etc/localtime:ro

      - ./database:/var/lib/postgresql
    restart: always

  kreuzstich-int-api:
    container_name: kreuzstich-int-api
    depends_on:
      - kreuzstich-int-database
    image: ghcr.io/polletfa/kreuzstich-int-api:latest
    env_file:
      # For environment variables that should not be committed:
      # - POSTGRES_PASSWORD (kreuzstich-int-database)
      # - KREUZSTICH_DATA_WEB_DB_PASSWORD (kreuzstich-int-api)
      # - KREUZSTICH_DATA_WEB_JWT_SECRET (kreuzstich-int-api)
      - ./secrets.env
    environment:
      - KREUZSTICH_DATA_WEB_PORT=80
      - KREUZSTICH_DATA_WEB_DB_HOST=kreuzstich-int-database
      - KREUZSTICH_DATA_WEB_DB_DB=kreuzstich
      - KREUZSTICH_DATA_WEB_DB_USER=kreuzstich
    networks:
        - kreuzstich-int-backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  kreuzstich-int:
    container_name: kreuzstich-int
    depends_on:
      - kreuzstich-int-api
    image: ghcr.io/polletfa/kreuzstich-int:latest
    networks:
      - kreuzstich-int
      - kreuzstich-int-backend
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always
