name: Build and Test (multiple platforms)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    #############################################################################
    # Build matrix                                                              #
    #############################################################################

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build (Windows, MVSC)
            build_type: Release
            os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            qt_arch: win64_msvc2022_64
            qt_host: windows

          - name: Build (Linux, GCC)
            build_type: Release
            os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            qt_arch: linux_gcc_64
            qt_host: linux

          - name: Build (Linux, clang)
            build_type: Release
            os: ubuntu-latest
            c_compiler: clang-19
            cpp_compiler: clang++-19
            qt_arch: linux_gcc_64
            qt_host: linux

          - name: Build (MacOS, clang)
            build_type: Release
            os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            qt_arch: clang_64
            qt_host: mac

    steps:

    #############################################################################
    # Install requirements                                                      #
    #############################################################################

    - name: Install Clang 19
      if: matrix.c_compiler == 'clang-19' && matrix.os == 'ubuntu-latest'
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 19

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.10.2'
        host: ${{ matrix.qt_host }}
        target: 'desktop'
        arch: ${{ matrix.qt_arch }}
        cache: true

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install EMSDK
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 5.0.7
        actions-cache-folder: 'emsdk-cache'

    #############################################################################
    # Configure and build                                                       #
    #############################################################################

    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    #############################################################################
    # Test                                                                      #
    #############################################################################

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target runtests

    - name: Test Report
      uses: test-summary/action@v2
      with:
        paths: |
            ${{ github.workspace }}/build/unittests-results.xml
            ${{ github.workspace }}/src/gui-web/build/test-results/vitest.xml
      if: always()

    #############################################################################
    # Install and upload artifacts                                              #
    #############################################################################

    - name: Install
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target install

    - name: Upload dist/
      uses: actions/upload-artifact@v4
      with:
          path: ${{ github.workspace }}/build/dist

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
          path: |
            ${{ github.workspace }}/build/unittests-results.xml
            ${{ github.workspace }}/src/gui-web/build/test-results/vitest.xml

    - name: Upload build files on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
          retention-days: 1
          name: debug-artifacts-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.c_compiler }}
          path: |
              ${{ github.workspace }}/build
              ${{ github.workspace }}/src/gui-web/build

    - name: Upload build files on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
          retention-days: 1
          name: debug-artifacts-${{ matrix.os }}-${{ matrix.build_type }}-${{ matrix.c_compiler }}
          path: |
              ${{ github.workspace }}/build
              ${{ github.workspace }}/src/gui-web/build

  #############################################################################
  # Summary job                                                               #
  #############################################################################

  all-checks-passed:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check all matrix jobs passed
        run: |
          if [ "${{ needs.build.result }}" != "success" ]; then
          exit 1
          fi
