name: Build and Test (multiple platforms)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    #############################################################################
    # Build matrix                                                              #
    #############################################################################

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build (Windows, MVSC)
            build_type: Release
            os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            qt_arch: win64_msvc2022_64
            qt_host: windows

          - name: Build (Linux, GCC)
            build_type: Release
            os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            qt_arch: linux_gcc_64
            qt_host: linux

          - name: Build (Linux, clang)
            build_type: Release
            os: ubuntu-latest
            c_compiler: clang-19
            cpp_compiler: clang++-19
            qt_arch: linux_gcc_64
            qt_host: linux

          - name: Build (MacOS, clang)
            build_type: Release
            os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            qt_arch: clang_64
            qt_host: mac

    steps:

    #############################################################################
    # Build                                                                     #
    #############################################################################

    - name: Checkout
      uses: actions/checkout@v6

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    #############################################################################
    # Test                                                                      #
    #############################################################################

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target runtests

    - name: Test Report
      uses: test-summary/action@v2
      with:
        paths: "build/test-results/*.xml"
      if: always()

    #############################################################################
    # Install and upload artifacts                                              #
    #############################################################################

    - name: Install
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target install

    - name: Artifact name suffix
      run: echo "ARTIFACT_SUFFIX=${{ matrix.os }}-${{ matrix.c_compiler }}-${GITHUB_SHA::8}" >> $GITHUB_ENV
      shell: bash

    - name: Upload dist/
      uses: actions/upload-artifact@v4
      with:
          name: dist-${{ env.ARTIFACT_SUFFIX }}
          path: build/dist

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
          name: test-results-${{ env.ARTIFACT_SUFFIX }}
          path: build/test-results

    - name: Upload build files on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
          retention-days: 1
          name: build-${{ env.ARTIFACT_SUFFIX }}
          path: |
              build
              src/gui-web/build

  #############################################################################
  # Summary job                                                               #
  #############################################################################

  all-checks-passed:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check all matrix jobs passed
        run: |
          if [ "${{ needs.build.result }}" != "success" ]; then
          exit 1
          fi
